// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pin.LiveSports.Infrastructure.Data;

#nullable disable

namespace Pin.LiveSports.Infrastructure.Migrations
{
    [DbContext(typeof(BoxingDbContext))]
    [Migration("20260604042049_UpdateRelations")]
    partial class UpdateRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoxingMatchFighter", b =>
                {
                    b.Property<Guid>("AssignedMatchesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FightersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssignedMatchesId", "FightersId");

                    b.HasIndex("FightersId");

                    b.ToTable("BoxingMatchFighter");
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.BoxingMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WinningFighterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BoxingMatches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6facfdcb-229d-4463-a5fc-a21e698d7b8b")
                        },
                        new
                        {
                            Id = new Guid("924a742c-a558-44c2-93dd-933526669e9c")
                        },
                        new
                        {
                            Id = new Guid("e0a5c2bb-658e-437a-9441-1ecfc5c2745d")
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.Fighter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fighters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bcd2113-9eb3-4a51-9811-334804296bbc"),
                            Firstname = "John",
                            Lastname = "Wick",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("0925d15b-ea3a-4b9c-b487-2a036940b4c7"),
                            Firstname = "Steven",
                            Lastname = "Hawk",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("e9e1782f-d6cd-4185-b971-d0eaf446d318"),
                            Firstname = "Bert",
                            Lastname = "Dert",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("e873df57-7506-477d-9034-6a931fe4c0bf"),
                            Firstname = "Dirk",
                            Lastname = "Hirk",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("25173fe0-9ebe-4e5c-a7f6-c9125feab2e8"),
                            Firstname = "Hol",
                            Lastname = "De Bol",
                            WeightClass = 2
                        },
                        new
                        {
                            Id = new Guid("50c7232b-dd2a-4071-a71b-b63b0537a389"),
                            Firstname = "Hank",
                            Lastname = "De Tank",
                            WeightClass = 2
                        });
                });

            modelBuilder.Entity("BoxingMatchFighter", b =>
                {
                    b.HasOne("Pin.LiveSports.Core.Entities.BoxingMatch", null)
                        .WithMany()
                        .HasForeignKey("AssignedMatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pin.LiveSports.Core.Entities.Fighter", null)
                        .WithMany()
                        .HasForeignKey("FightersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
