// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pin.LiveSports.Infrastructure.Data;

#nullable disable

namespace Pin.LiveSports.Infrastructure.Migrations
{
    [DbContext(typeof(BoxingDbContext))]
    [Migration("20260604154504_UpdateMatchFighterCount")]
    partial class UpdateMatchFighterCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.BoxingMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FighterBlueTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FighterRedTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WinningFighterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FighterBlueTeamId");

                    b.HasIndex("FighterRedTeamId");

                    b.ToTable("BoxingMatches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c4925c1-bf32-4722-b106-4533eb7a2f76"),
                            FighterBlueTeamId = new Guid("bbd94e0b-2ab2-4513-9b6d-b0c9e588d91e"),
                            FighterRedTeamId = new Guid("1cebe6c8-71c6-4c2e-8e3d-93b2dbe7a33f")
                        },
                        new
                        {
                            Id = new Guid("d40987e1-e648-41b3-b7bf-b649706118d0"),
                            FighterBlueTeamId = new Guid("13cd89c1-b0f8-4528-b48a-b88a57613be0"),
                            FighterRedTeamId = new Guid("e09ee730-91d2-4207-ae38-573bfc6d1dc2")
                        },
                        new
                        {
                            Id = new Guid("15f76db9-82eb-41f7-8722-1ea05c1870d0"),
                            FighterBlueTeamId = new Guid("f6058402-76c6-4531-9723-f00c23d5a7ab"),
                            FighterRedTeamId = new Guid("3eee2aef-7794-4660-a539-e66c161778b4")
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.Fighter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fighters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbd94e0b-2ab2-4513-9b6d-b0c9e588d91e"),
                            Firstname = "John",
                            Lastname = "Wick",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("1cebe6c8-71c6-4c2e-8e3d-93b2dbe7a33f"),
                            Firstname = "Steven",
                            Lastname = "Hawk",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("13cd89c1-b0f8-4528-b48a-b88a57613be0"),
                            Firstname = "Bert",
                            Lastname = "Dert",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("e09ee730-91d2-4207-ae38-573bfc6d1dc2"),
                            Firstname = "Dirk",
                            Lastname = "Hirk",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("f6058402-76c6-4531-9723-f00c23d5a7ab"),
                            Firstname = "Hol",
                            Lastname = "De Bol",
                            WeightClass = 2
                        },
                        new
                        {
                            Id = new Guid("3eee2aef-7794-4660-a539-e66c161778b4"),
                            Firstname = "Hank",
                            Lastname = "De Tank",
                            WeightClass = 2
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.BoxingMatch", b =>
                {
                    b.HasOne("Pin.LiveSports.Core.Entities.Fighter", "FighterBlueTeam")
                        .WithMany()
                        .HasForeignKey("FighterBlueTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pin.LiveSports.Core.Entities.Fighter", "FighterRedTeam")
                        .WithMany()
                        .HasForeignKey("FighterRedTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FighterBlueTeam");

                    b.Navigation("FighterRedTeam");
                });
#pragma warning restore 612, 618
        }
    }
}
