// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pin.LiveSports.Infrastructure.Data;

#nullable disable

namespace Pin.LiveSports.Infrastructure.Migrations
{
    [DbContext(typeof(BoxingDbContext))]
    [Migration("20260608121945_UpdateBoxingMatchIsFinished")]
    partial class UpdateBoxingMatchIsFinished
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.BoxingMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FighterBlueTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FighterRedTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<Guid?>("WinningFighterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FighterBlueTeamId");

                    b.HasIndex("FighterRedTeamId");

                    b.HasIndex("WinningFighterId");

                    b.ToTable("BoxingMatches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be50d345-3722-479c-b861-d3aee5e25899"),
                            FighterBlueTeamId = new Guid("058ef8d9-05f7-413e-bba7-b1f3416243e7"),
                            FighterRedTeamId = new Guid("a5535f2d-cf6f-4566-89ed-6eaf6ddeed7b"),
                            IsFinished = false
                        },
                        new
                        {
                            Id = new Guid("e98a7217-ac1a-4f65-abe1-60a1fd99e5d7"),
                            FighterBlueTeamId = new Guid("11789088-b402-4844-b878-424c9385dd78"),
                            FighterRedTeamId = new Guid("0f3a379f-ba4e-4f3a-afdf-6173f789fae4"),
                            IsFinished = false
                        },
                        new
                        {
                            Id = new Guid("d618d38e-2539-42cb-96aa-34abf481573d"),
                            FighterBlueTeamId = new Guid("e1e24754-cebe-4de3-a500-186215bcb503"),
                            FighterRedTeamId = new Guid("a5431437-e100-4056-bb5c-85a7596e1496"),
                            IsFinished = false
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.Fighter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fighters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("058ef8d9-05f7-413e-bba7-b1f3416243e7"),
                            Firstname = "John",
                            Lastname = "Wick",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("a5535f2d-cf6f-4566-89ed-6eaf6ddeed7b"),
                            Firstname = "Steven",
                            Lastname = "Hawk",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("11789088-b402-4844-b878-424c9385dd78"),
                            Firstname = "Bert",
                            Lastname = "Dert",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("0f3a379f-ba4e-4f3a-afdf-6173f789fae4"),
                            Firstname = "Dirk",
                            Lastname = "Hirk",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("e1e24754-cebe-4de3-a500-186215bcb503"),
                            Firstname = "Hol",
                            Lastname = "De Bol",
                            WeightClass = 2
                        },
                        new
                        {
                            Id = new Guid("a5431437-e100-4056-bb5c-85a7596e1496"),
                            Firstname = "Hank",
                            Lastname = "De Tank",
                            WeightClass = 2
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.BoxingMatch", b =>
                {
                    b.HasOne("Pin.LiveSports.Core.Entities.Fighter", "FighterBlueTeam")
                        .WithMany()
                        .HasForeignKey("FighterBlueTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pin.LiveSports.Core.Entities.Fighter", "FighterRedTeam")
                        .WithMany()
                        .HasForeignKey("FighterRedTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pin.LiveSports.Core.Entities.Fighter", "WinningFighter")
                        .WithMany()
                        .HasForeignKey("WinningFighterId");

                    b.Navigation("FighterBlueTeam");

                    b.Navigation("FighterRedTeam");

                    b.Navigation("WinningFighter");
                });
#pragma warning restore 612, 618
        }
    }
}
