// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pin.LiveSports.Infrastructure.Data;

#nullable disable

namespace Pin.LiveSports.Infrastructure.Migrations
{
    [DbContext(typeof(BoxingDbContext))]
    [Migration("20260604161100_UpdateMatchWinningFighter")]
    partial class UpdateMatchWinningFighter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.BoxingMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FighterBlueTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FighterRedTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WinningFighterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FighterBlueTeamId");

                    b.HasIndex("FighterRedTeamId");

                    b.HasIndex("WinningFighterId");

                    b.ToTable("BoxingMatches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24576417-aeb9-4947-8df4-0ed9eab9d4ab"),
                            FighterBlueTeamId = new Guid("fa509d86-3ddb-4a31-b80b-25758d6cc830"),
                            FighterRedTeamId = new Guid("46a8c0d0-e6a7-4954-b08f-a5337376a067")
                        },
                        new
                        {
                            Id = new Guid("5b780773-4719-4d62-8a2d-536b02b2d22e"),
                            FighterBlueTeamId = new Guid("13530808-43cf-4c29-9f48-826abc9f9128"),
                            FighterRedTeamId = new Guid("ca7541a9-1ec2-471b-9679-e487eba1ffb4")
                        },
                        new
                        {
                            Id = new Guid("4b53ff50-d19f-408c-881a-b390ca0982cc"),
                            FighterBlueTeamId = new Guid("06e38bef-6168-489d-933e-b7028ef421d1"),
                            FighterRedTeamId = new Guid("f461b887-30cd-49e1-9967-8d7b633a6072")
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.Fighter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fighters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa509d86-3ddb-4a31-b80b-25758d6cc830"),
                            Firstname = "John",
                            Lastname = "Wick",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("46a8c0d0-e6a7-4954-b08f-a5337376a067"),
                            Firstname = "Steven",
                            Lastname = "Hawk",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("13530808-43cf-4c29-9f48-826abc9f9128"),
                            Firstname = "Bert",
                            Lastname = "Dert",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("ca7541a9-1ec2-471b-9679-e487eba1ffb4"),
                            Firstname = "Dirk",
                            Lastname = "Hirk",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("06e38bef-6168-489d-933e-b7028ef421d1"),
                            Firstname = "Hol",
                            Lastname = "De Bol",
                            WeightClass = 2
                        },
                        new
                        {
                            Id = new Guid("f461b887-30cd-49e1-9967-8d7b633a6072"),
                            Firstname = "Hank",
                            Lastname = "De Tank",
                            WeightClass = 2
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.BoxingMatch", b =>
                {
                    b.HasOne("Pin.LiveSports.Core.Entities.Fighter", "FighterBlueTeam")
                        .WithMany()
                        .HasForeignKey("FighterBlueTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pin.LiveSports.Core.Entities.Fighter", "FighterRedTeam")
                        .WithMany()
                        .HasForeignKey("FighterRedTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pin.LiveSports.Core.Entities.Fighter", "WinningFighter")
                        .WithMany()
                        .HasForeignKey("WinningFighterId");

                    b.Navigation("FighterBlueTeam");

                    b.Navigation("FighterRedTeam");

                    b.Navigation("WinningFighter");
                });
#pragma warning restore 612, 618
        }
    }
}
