// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pin.LiveSports.Infrastructure.Data;

#nullable disable

namespace Pin.LiveSports.Infrastructure.Migrations
{
    [DbContext(typeof(BoxingDbContext))]
    [Migration("20260604042538_UpdateWithFluentAPI")]
    partial class UpdateWithFluentAPI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoxingMatchFighter", b =>
                {
                    b.Property<Guid>("AssignedMatchesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FightersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssignedMatchesId", "FightersId");

                    b.HasIndex("FightersId");

                    b.ToTable("BoxingMatchFighter");
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.BoxingMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WinningFighterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BoxingMatches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c0d65e8-400b-4e2e-b3ed-10b2d6c0eb6f")
                        },
                        new
                        {
                            Id = new Guid("996159ef-db19-47a2-999f-d17a7fb669d6")
                        },
                        new
                        {
                            Id = new Guid("177b8f2f-aaf9-4b74-984a-2dea3a8829b6")
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.Fighter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fighters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e84a0bee-047b-400c-9e71-0c3c7b6e2735"),
                            Firstname = "John",
                            Lastname = "Wick",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("989fe019-952a-401b-9ed4-5868eb6c59d0"),
                            Firstname = "Steven",
                            Lastname = "Hawk",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("7e177a58-5214-4e24-95e5-d6bdd36b138b"),
                            Firstname = "Bert",
                            Lastname = "Dert",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("dc39c6fa-9ebc-49c4-9590-36588a8f7f69"),
                            Firstname = "Dirk",
                            Lastname = "Hirk",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("42f061a1-1a4f-4ae4-b334-0cbb01c0299f"),
                            Firstname = "Hol",
                            Lastname = "De Bol",
                            WeightClass = 2
                        },
                        new
                        {
                            Id = new Guid("976db6d2-7b3c-4cdb-8524-7f171b8471f4"),
                            Firstname = "Hank",
                            Lastname = "De Tank",
                            WeightClass = 2
                        });
                });

            modelBuilder.Entity("BoxingMatchFighter", b =>
                {
                    b.HasOne("Pin.LiveSports.Core.Entities.BoxingMatch", null)
                        .WithMany()
                        .HasForeignKey("AssignedMatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pin.LiveSports.Core.Entities.Fighter", null)
                        .WithMany()
                        .HasForeignKey("FightersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
