// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pin.LiveSports.Infrastructure.Data;

#nullable disable

namespace Pin.LiveSports.Infrastructure.Migrations
{
    [DbContext(typeof(BoxingDbContext))]
    [Migration("20260604135654_UpdateManyToManyData")]
    partial class UpdateManyToManyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoxingMatchFighter", b =>
                {
                    b.Property<Guid>("AssignedMatchesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FightersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssignedMatchesId", "FightersId");

                    b.HasIndex("FightersId");

                    b.ToTable("BoxingMatchFighter");

                    b.HasData(
                        new
                        {
                            AssignedMatchesId = new Guid("e9645c58-fc32-4823-af8e-c6f690f46ae1"),
                            FightersId = new Guid("2935d557-c9e3-4e33-8983-32760bb1739d")
                        },
                        new
                        {
                            AssignedMatchesId = new Guid("e9645c58-fc32-4823-af8e-c6f690f46ae1"),
                            FightersId = new Guid("76eea230-03d7-4b86-8a42-48a8345d3b98")
                        },
                        new
                        {
                            AssignedMatchesId = new Guid("4582fef0-ff06-4794-bb4f-2553a593e0e8"),
                            FightersId = new Guid("72dfcb59-5548-49ab-8105-965d63f8cb4e")
                        },
                        new
                        {
                            AssignedMatchesId = new Guid("4582fef0-ff06-4794-bb4f-2553a593e0e8"),
                            FightersId = new Guid("e9063b97-4348-4a0f-afe2-a5de25509f91")
                        },
                        new
                        {
                            AssignedMatchesId = new Guid("f304d9be-e015-4c98-b1b2-f36d9cae6890"),
                            FightersId = new Guid("698fe98a-78c1-4498-92e9-e8d4dc95b95e")
                        },
                        new
                        {
                            AssignedMatchesId = new Guid("f304d9be-e015-4c98-b1b2-f36d9cae6890"),
                            FightersId = new Guid("ece87e48-3cad-4cd4-9a53-f5b6bb5aa1d8")
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.BoxingMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WinningFighterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BoxingMatches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9645c58-fc32-4823-af8e-c6f690f46ae1")
                        },
                        new
                        {
                            Id = new Guid("4582fef0-ff06-4794-bb4f-2553a593e0e8")
                        },
                        new
                        {
                            Id = new Guid("f304d9be-e015-4c98-b1b2-f36d9cae6890")
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.Fighter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fighters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2935d557-c9e3-4e33-8983-32760bb1739d"),
                            Firstname = "John",
                            Lastname = "Wick",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("76eea230-03d7-4b86-8a42-48a8345d3b98"),
                            Firstname = "Steven",
                            Lastname = "Hawk",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("72dfcb59-5548-49ab-8105-965d63f8cb4e"),
                            Firstname = "Bert",
                            Lastname = "Dert",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("e9063b97-4348-4a0f-afe2-a5de25509f91"),
                            Firstname = "Dirk",
                            Lastname = "Hirk",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("698fe98a-78c1-4498-92e9-e8d4dc95b95e"),
                            Firstname = "Hol",
                            Lastname = "De Bol",
                            WeightClass = 2
                        },
                        new
                        {
                            Id = new Guid("ece87e48-3cad-4cd4-9a53-f5b6bb5aa1d8"),
                            Firstname = "Hank",
                            Lastname = "De Tank",
                            WeightClass = 2
                        });
                });

            modelBuilder.Entity("BoxingMatchFighter", b =>
                {
                    b.HasOne("Pin.LiveSports.Core.Entities.BoxingMatch", null)
                        .WithMany()
                        .HasForeignKey("AssignedMatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pin.LiveSports.Core.Entities.Fighter", null)
                        .WithMany()
                        .HasForeignKey("FightersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
