// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pin.LiveSports.Infrastructure.Data;

#nullable disable

namespace Pin.LiveSports.Infrastructure.Migrations
{
    [DbContext(typeof(BoxingDbContext))]
    partial class BoxingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.BoxingMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FighterOneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FighterTwoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WinningFighterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BoxingMatches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd50538d-554c-4909-8ef6-8dade75d3098"),
                            FighterOneId = new Guid("e0093bac-06f3-4665-8aa5-05818fd29578"),
                            FighterTwoId = new Guid("56ca7c74-52c1-40be-9468-b8006d127ce7")
                        },
                        new
                        {
                            Id = new Guid("ed5254ac-3f4e-4814-b3ab-00b99c6bb8b1"),
                            FighterOneId = new Guid("04cd5d5e-4bce-428e-9bff-b7caec1e13ab"),
                            FighterTwoId = new Guid("1785951f-93c4-491b-af87-af4c0f8304bd")
                        },
                        new
                        {
                            Id = new Guid("5702ca16-a921-4309-9a33-908f58688a8f"),
                            FighterOneId = new Guid("8b9e5957-c908-4501-a98d-fc38fa82945a"),
                            FighterTwoId = new Guid("a25af6f4-ee7e-4193-91a1-1d7fcfdb3089")
                        });
                });

            modelBuilder.Entity("Pin.LiveSports.Core.Entities.Fighter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fighters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0093bac-06f3-4665-8aa5-05818fd29578"),
                            Firstname = "John",
                            Lastname = "Wick",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("56ca7c74-52c1-40be-9468-b8006d127ce7"),
                            Firstname = "Steven",
                            Lastname = "Hawk",
                            WeightClass = 0
                        },
                        new
                        {
                            Id = new Guid("04cd5d5e-4bce-428e-9bff-b7caec1e13ab"),
                            Firstname = "Bert",
                            Lastname = "Dert",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("1785951f-93c4-491b-af87-af4c0f8304bd"),
                            Firstname = "Dirk",
                            Lastname = "Hirk",
                            WeightClass = 1
                        },
                        new
                        {
                            Id = new Guid("8b9e5957-c908-4501-a98d-fc38fa82945a"),
                            Firstname = "Hol",
                            Lastname = "De Bol",
                            WeightClass = 2
                        },
                        new
                        {
                            Id = new Guid("a25af6f4-ee7e-4193-91a1-1d7fcfdb3089"),
                            Firstname = "Hank",
                            Lastname = "De Tank",
                            WeightClass = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
